### ISSUE TITLE
make uninstall as root runs 'rm -f /'

### ISSUE THREAD

**Issue by andybeta** [waveform80/db2utils#11]
User accidentally ran "make uninstall" as root
make uninstall unicode and pcre has 
DB2PATH:=$(shell getent passwd ${DB2INSTANCE} | cut -d':' -f6)/sqllib
if DB2INSTANCE is null then getent passwd returns every home directory in /etc/passwd and only appends 'sqllib' to the last line

uninstall: 
then appends '/function/pcre_udfs' to the last line, and then runs 
rm -f on every line in turn.

On our system this deleted /bin and /sbin (symlinks on RH7)

**Comment by waveform80** [comment]
Ouch - sorry about that. I'll stick in a check to make sure it blows up if DB2INSTANCE is blank (in the affected makefiles)
